### PR TITLE
Issue#6 fix

### LINKED ISSUE #6: Estimation is yielding 0 values.
When GEOS tries to estimate the performance after applying some optimization sequences, it returns ZERO, sometimes.

### PR DESCRIPTION
**Pull request by YuKill**
#6 was successfully fixed. The instructions were able to store the frequency so that, when propagated to the basic block, the cost generated wouldn't yield 0.
Perhaps it still needs some polishing, i.e. to make the frequencies consistent.

### CODE REVIEW

File: include/ProfileModule/PassSequence.h [hunk 1]
```diff
@@ -300,7 +300,7 @@ class PassSequence {
     unsigned size() const {
       return Opts.size();
     }
-
```
Comment (vandersonmr) [inline include/ProfileModule/PassSequence.h]: is this the only modification on this file? If so, It shouldn't be committed.

File: tools/CMakeLists.txt [hunk 2]
```diff
@@ -83,5 +83,6 @@ TARGET_LINK_LIBRARIES(geos-metric GEOS CostEstimator GCOV STATIC ProfileModule
   LLVMMCJIT LLVMRuntimeDyld LLVMInterpreter LLVMExecutionEngine  
   rt dl tinfo atomic pthread papi z m)
 
+
```
Comment (vandersonmr) [inline tools/CMakeLists.txt]: Again. Just one empty line.

**Comment by vandersonmr** [comment]
Also, as you remember me last time, you should commit it to the 2.0 branch too.
